### ISSUE TITLE
Missing segment to bus stop

### ISSUE THREAD

**Issue by thohug** [datamapio/posmo_one_testing#2]
**Setting**
Zurich, Switzerland, Android

geofence: 0
do_not_track: 0
wifi_over_gps: 0
data_over_wifi_only: 0

**Issue**

Segment to bus stop wasn't recognised (~8pm, walking). Bus segment was changed manually from bike to bus.

![grafik](https://user-images.githubusercontent.com/67195528/85203748-10bea680-b310-11ea-9c82-3158fad1ea6c.png)

**Comment by djr4** [comment]
Processed with new backend:
<img width="663" alt="Screen Shot 2020-06-21 at 1 48 44 AM" src="https://user-images.githubusercontent.com/6351012/85213656-712a0400-b361-11ea-9462-c5841918b773.png">

Does this seam correct to you now?
