### ISSUE TITLE
Lost GPS in Tunnel leads to confusion

### ISSUE THREAD

**Issue by thohug** [datamapio/posmo_one_testing#4]
**Setting**
Zurich, Switzerland, Android

geofence: 0
do_not_track: 0
wifi_over_gps: 0
data_over_wifi_only: 0

**Issue**

Using the train in a tunnel leads to a lost GPS signal and a broken up segment. Too many segments are created. Distance of 2nd train segment doesn't seem right.

![grafik](https://user-images.githubusercontent.com/67195528/85203886-db668880-b310-11ea-8746-bbad71bfb226.png)

**Comment by djr4** [comment]
Note, current backend:
<img width="623" alt="Screen Shot 2020-06-21 at 2 11 51 AM" src="https://user-images.githubusercontent.com/6351012/85213894-9bc98c00-b364-11ea-8aaa-d1e5195c9cdc.png">

This is harder, we should collect more examples and see what is the pattern here.

**Comment by djr4** [comment]
<img width="548" alt="Screen Shot 2020-06-21 at 5 55 59 PM" src="https://user-images.githubusercontent.com/6351012/85229451-04a71780-b3ea-11ea-9648-655f7d2f878c.png">

will be deployed with new backend. This looks good (accurate)?

**Comment by rogerfischer** [comment]
That sounds about right:
<img width="1099" alt="Screen Shot 2020-06-22 at 9 55 30 AM" src="https://user-images.githubusercontent.com/7697124/85262795-92c4e180-b46e-11ea-9d27-f6efea4abf63.png">

**Comment by djr4** [comment]
ok we close this issue, trains are tricky (so it could be reoccurring) so if something new arrises open up separate issue. Thanks.
